// src/lib/components/Hero.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'
  import { buttonVariants } from '@/lib/components/ui/Button.svelte'
  import Content from '@/lib/components/ui/Content.svelte'
  import Heading from '@/lib/components/ui/Heading.svelte'
  import { Routes } from '@/lib/types/misc'
  import { cn } from '@/lib/utils/misc'
  import Socials from '@/lib/components/Socials.svelte'

  const { class: className, ...props }: HTMLAttributes<HTMLElement> = $props()
</script>

<section class={cn('bg-ghost pt-header dark:bg-dark relative h-[100dvh]', className)} {...props}>
  <enhanced:img
    class="absolute top-0 left-0 z-0 h-full w-full object-cover object-center"
    src="../assets/hero-bg.svg"
    alt="Page Background"
  />

  <Content
    class="relative z-[1] flex flex-col items-center justify-center text-center"
    size="tight"
  >
    <article>
      <Heading position="center">
        Hi, I&apos;m <span class="text-accent">Anton Bochkovskyi</span>
      </Heading>

      <p class="mt-4 text-lg font-medium md:text-xl">
        Motivated Front-End Developer with a passion for creating engaging, elegant and responsive
        user interfaces.
      </p>
    </article>

    <a class={cn('mt-5', buttonVariants({ variant: 'outline' }))} href={Routes.Projects}>
      My Projects
    </a>
  </Content>

  <Socials class="absolute bottom-8 left-8 hidden md:flex" orientation="vertical" />
</section>

// src/components/pages/hero.tsx
import Button from '@/components/ui/button'
import Content from '@/components/ui/content'
import Socials from '@/components/ui/socials/socials'
import { classnames } from '@/utils'
import { FC } from 'react'

import styles from './hero.module.css'

const Hero: FC = () => {
  return (
    <section
      className={classnames(
        'relative bg-ghost dark:bg-dark',
        styles['hero-container']
      )}
    >
      <Content className="flex flex-col items-center justify-center text-center">
        <div className="max-w-4xl">
          <h1 className="text-4xl font-bold md:text-5xl">
            Hi, I&apos;m <span className="text-accent">Anton Bochkovskyi</span>
          </h1>
          <p className="mt-4 font-medium md:text-xl">
            Motivated Junior Front-End Developer with a passion for creating
            engaging, elegant and responsive user interfaces.
          </p>
        </div>
        <Button className="mt-5" variant="outline">
          My Work
        </Button>
      </Content>
      <Socials className="absolute bottom-2.5 left-1/2 -translate-x-1/2" />
    </section>
  )
}

export default Hero
