// src/components/sections/hero/hero.tsx
import Image from 'next/image'
import Link from 'next/link'
import { FC, HTMLAttributes } from 'react'

import { buttonVariants } from '@/components/ui/button'
import Content from '@/components/ui/content'
import Heading from '@/components/ui/heading'
import Socials from '@/components/ui/socials'
import { LINK } from '@/types/enums/Link'
import { cn } from '@/utils'

const Hero: FC<HTMLAttributes<HTMLDivElement>> = ({ className, ...props }) => {
  return (
    <section
      className={cn(
        'relative h-[100dvh] bg-ghost pt-header dark:bg-dark',
        className
      )}
      {...props}
    >
      <Image
        alt="Background"
        className="-z-5 object-cover object-center"
        fill
        sizes="100vw"
        src="/hero-bg.svg"
      />
      <Content
        className="relative flex flex-col items-center justify-center text-center"
        size="tight"
      >
        <article>
          <Heading position="center">
            Hi, I&apos;m <span className="text-accent">Anton Bochkovskyi</span>
          </Heading>
          <p className="mt-4 text-lg font-medium md:text-xl">
            Motivated Front-End Developer with a passion for creating engaging,
            elegant and responsive user interfaces.
          </p>
        </article>
        <Link
          className={cn('mt-5', buttonVariants({ variant: 'outline' }))}
          href={LINK.projects}
        >
          My Projects
        </Link>
      </Content>
      <Socials
        className="absolute bottom-8 left-8 hidden md:flex"
        orientation="vertical"
      />
    </section>
  )
}

export default Hero

// src/lib/components/Hero.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'
  import { buttonVariants } from '@/lib/components/ui/Button.svelte'
  import Content from '@/lib/components/ui/Content.svelte'
  import Heading from '@/lib/components/ui/Heading.svelte'
  import { Routes } from '@/lib/types/misc'
  import { cn } from '@/lib/utils/misc'
  import Socials from '@/lib/components/Socials.svelte'

  const { class: className, ...props }: HTMLAttributes<HTMLElement> = $props()
</script>

<section class={cn('bg-ghost pt-header dark:bg-dark relative h-[100dvh]', className)} {...props}>
  <enhanced:img
    class="absolute top-0 left-0 z-0 h-full w-full object-cover object-center"
    src="../assets/hero-bg.svg"
    alt="Page Background"
  />

  <Content
    class="relative z-[1] flex flex-col items-center justify-center text-center"
    size="tight"
  >
    <article>
      <Heading position="center">
        Hi, I&apos;m <span class="text-accent">Anton Bochkovskyi</span>
      </Heading>

      <p class="mt-4 text-lg font-medium md:text-xl">
        Motivated Front-End Developer with a passion for creating engaging, elegant and responsive
        user interfaces.
      </p>
    </article>

    <a class={cn('mt-5', buttonVariants({ variant: 'outline' }))} href={Routes.Projects}>
      My Projects
    </a>
  </Content>

  <Socials class="absolute bottom-8 left-8 hidden md:flex" orientation="vertical" />
</section>
