// src/components/UI/Socials/Socials.tsx
import { FC } from 'react'
import { classnames } from '@/utils'
import { FaGithub, FaLinkedin } from 'react-icons/fa'
import SocialsItem from './SocialsItem'

type SocialsProps = {
  className?: string
}

const Socials: FC<SocialsProps> = ({ className }) => {
  return (
    <ul className={classnames('p-5 flex gap-8', className)}>
      <SocialsItem href="https://www.linkedin.com/in/anton-bochkovskyi/">
        <FaLinkedin />
      </SocialsItem>
      <SocialsItem href="https://github.com/firehawk89">
        <FaGithub />
      </SocialsItem>
    </ul>
  )
}

export default Socials

// src/lib/components/Socials.svelte
<script lang="ts">
  import type { IconsListProps } from '@/lib/components/ui/icon-list/IconList.svelte'
  import IconList from '@/lib/components/ui/icon-list/IconList.svelte'
  import IconListItem from '@/lib/components/ui/icon-list/IconListItem.svelte'

  const props: IconsListProps = $props()
</script>

<IconList {...props}>
  <IconListItem
    icon="icon-[mdi--linkedin]"
    href="https://www.linkedin.com/in/anton-bochkovskyi/"
    title="LinkedIn"
  />
  <IconListItem icon="icon-[mdi--github]" href="https://github.com/firehawk89" title="GitHub" />
</IconList>
