// src/components/ui/socials/socials.tsx
import SocialsItem from '@/components/ui/socials/socials-item'
import { classnames } from '@/utils'
import { FC } from 'react'
import { FaGithub, FaLinkedin } from 'react-icons/fa'

type SocialsProps = {
  className?: string
}

const Socials: FC<SocialsProps> = ({ className }) => {
  return (
    <ul className={classnames('p-5 flex gap-8', className)}>
      <SocialsItem
        Icon={FaLinkedin}
        href="https://www.linkedin.com/in/anton-bochkovskyi/"
        title="LinkedIn"
      />
      <SocialsItem
        Icon={FaGithub}
        href="https://github.com/firehawk89"
        title="GitHub"
      />
    </ul>
  )
}

export default Socials

// src/lib/components/Socials.svelte
<script lang="ts">
  import type { IconsListProps } from '@/lib/components/ui/icon-list/IconList.svelte'
  import IconList from '@/lib/components/ui/icon-list/IconList.svelte'
  import IconListItem from '@/lib/components/ui/icon-list/IconListItem.svelte'

  const props: IconsListProps = $props()
</script>

<IconList {...props}>
  <IconListItem
    icon="icon-[mdi--linkedin]"
    href="https://www.linkedin.com/in/anton-bochkovskyi/"
    title="LinkedIn"
  />
  <IconListItem icon="icon-[mdi--github]" href="https://github.com/firehawk89" title="GitHub" />
</IconList>
