// src/components/ui/socials.tsx
import { FC } from 'react'
import { FaGithub, FaLinkedin } from 'react-icons/fa'

import IconsList, {
  IconsListProps,
} from '@/components/ui/icons-list/icons-list'
import IconsListItem from '@/components/ui/icons-list/icons-list-item'

const Socials: FC<IconsListProps> = ({ ...props }) => {
  return (
    <IconsList {...props}>
      <IconsListItem
        Icon={FaLinkedin}
        href="https://www.linkedin.com/in/anton-bochkovskyi/"
        title="LinkedIn"
      />
      <IconsListItem
        Icon={FaGithub}
        href="https://github.com/firehawk89"
        title="GitHub"
      />
    </IconsList>
  )
}

export default Socials

// src/lib/components/Socials.svelte
<script lang="ts">
  import type { IconsListProps } from '@/lib/components/ui/icon-list/IconList.svelte'
  import IconList from '@/lib/components/ui/icon-list/IconList.svelte'
  import IconListItem from '@/lib/components/ui/icon-list/IconListItem.svelte'

  const props: IconsListProps = $props()
</script>

<IconList {...props}>
  <IconListItem
    icon="icon-[mdi--linkedin]"
    href="https://www.linkedin.com/in/anton-bochkovskyi/"
    title="LinkedIn"
  />
  <IconListItem icon="icon-[mdi--github]" href="https://github.com/firehawk89" title="GitHub" />
</IconList>
