// src/lib/components/ui/Button.svelte
<script lang="ts" module>
  import { type VariantProps, cva } from 'class-variance-authority'
  import type { HTMLButtonAttributes } from 'svelte/elements'

  export const buttonVariants = cva(
    'font-medium transition-all active:scale-95 md:text-lg disabled:pointer-events-none',
    {
      defaultVariants: {
        size: 'default',
        variant: 'default'
      },
      variants: {
        size: {
          default: 'block w-fit py-2 px-5 rounded-md',
          sm: 'block w-fit p-2'
        },
        variant: {
          default:
            'border-2 border-accent bg-accent text-light md:hover:bg-accent-light disabled:border-accent-light disabled:bg-accent-light md:hover:border-accent-light',
          icon: 'bg-transparent md:hover:text-accent',
          outline:
            'border-2 border-accent bg-transparent text-accent disabled:border-accent-light disabled:text-accent-light md:hover:bg-accent md:hover:text-light'
        }
      }
    }
  )

  export interface ButtonProps extends HTMLButtonAttributes, VariantProps<typeof buttonVariants> {}
</script>

<script lang="ts">
  import { cn } from '@/lib/utils/misc'

  const { children, class: className, size, variant, ...props }: ButtonProps = $props()
</script>

<button class={cn(buttonVariants({ size, variant }), className)} {...props}>
  {@render children?.()}
</button>

// src/components/UI/Button.tsx
import { FC, ReactNode } from 'react'
import { classnames } from '@/utils'
import Link from 'next/link'

type ButtonVariant = 'solid' | 'outline'

type ButtonProps = {
  children: ReactNode
  className?: string
  type?: 'button' | 'submit' | 'reset'
  disabled?: boolean
  variant?: ButtonVariant
  href?: string
  onClick?: () => void
}

const buttonStyles: Record<ButtonVariant, string> = {
  solid: 'text-light bg-accent md:hover:bg-opacity-80',
  outline: 'text-accent bg-transparent md:hover:text-light md:hover:bg-accent',
}

const Button: FC<ButtonProps> = ({
  children,
  className,
  type = 'button',
  disabled,
  variant = 'solid',
  href,
  onClick,
}) => {
  return (
    <>
      {href ? (
        <Link
          className={classnames(
            'px-5 py-2 rounded-md border-2 border-accent text-lg font-medium transition-all active:scale-95',
            buttonStyles[variant],
            className
          )}
          href={href}
        >
          {children}
        </Link>
      ) : (
        <button
          className={classnames(
            'px-5 py-2 rounded-md border-2 border-accent md:text-lg font-medium transition-all active:scale-95',
            buttonStyles[variant],
            className
          )}
          type={type}
          disabled={disabled}
          onClick={onClick}
        >
          {children}
        </button>
      )}
    </>
  )
}

export default Button
